name: geng
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - cmake=3.27
  - pip:
    - -r requirements.txt