name: geng
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - cmake=3.27
  - pip:
    - imageio==2.37.3
    - huggingface-hub==0.35.3
    - libero==0.1.1
    - lerobot==0.4.4
    - num2words==0.5.14